# Generated by Django 5.1.3 on 2025-05-07 01:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_alter_review_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='gender',
            field=models.CharField(choices=[('GENERO', 'Genero'), ('ACCION', 'Acción'), ('AVENTURA', 'Aventura'), ('ESTRATEGIA', 'Estrategia'), ('RPG', 'RPG'), ('SIMULADOR', 'Simulador'), ('DEPORTES', 'Deportes'), ('PUZZLES', 'Puzzles'), ('SANDBOX', 'Sandbox'), ('SANDBOX', 'Sandbox'), ('ARCADE', 'Arcade'), ('MOBA', 'MOBA'), ('SHOOTER', 'Shooter'), ('JUEGOS_MUSICALES', 'Juegos Musicales'), ('SUPERVIVENCIAS', 'Supervivencias'), ('SOULSLIKE', 'Soulslike')], default='GENERO', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('blog', 'reviewer')},
        ),
    ]
