# Generated by Django 5.1.3 on 2025-05-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_blog_gender_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='gender',
            field=models.CharField(choices=[('GENERO', 'Genero'), ('ACCION', 'Acción'), ('AVENTURA', 'Aventura'), ('ESTRATEGIA', 'Estrategia'), ('RPG', 'RPG'), ('SIMULADOR', 'Simulador'), ('DEPORTES', 'Deportes'), ('PUZZLES', 'Puzzles'), ('SANDBOX', 'Sandbox'), ('ARCADE', 'Arcade'), ('MOBA', 'MOBA'), ('SHOOTER', 'Shooter'), ('JUEGOS_MUSICALES', 'Juegos Musicales'), ('SUPERVIVENCIAS', 'Supervivencias'), ('SOULSLIKE', 'Soulslike')], default='GENERO', max_length=20),
        ),
    ]
