# Generated by Django 5.1.3 on 2025-05-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_rename_gender_blog_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='genre',
            field=models.CharField(choices=[('ACCION', 'Acción'), ('AVENTURA', 'Aventura'), ('ESTRATEGIA', 'Estrategia'), ('RPG', 'RPG'), ('SIMULADOR', 'Simulador'), ('DEPORTES', 'Deportes'), ('PUZZLES', 'Puzzles'), ('SANDBOX', 'Sandbox'), ('ARCADE', 'Arcade'), ('MOBA', 'MOBA'), ('SHOOTER', 'Shooter'), ('JUEGOS_MUSICALES', 'Juegos Musicales'), ('SUPERVIVENCIAS', 'Supervivencias'), ('SOULSLIKE', 'Soulslike')], max_length=20),
        ),
    ]
